#!/bin/bash
clear
server='127.0.0.1'
port='3000'


hb(){
clear
echo "Heartbeat is now checking....."
curl -s $server:$port/hb
logs
}

stop(){
clear
echo "Stopping the containers....."
curl -s  http://$server:$port/stop
logs
}

start(){
clear
echo "Starting the containers....."
curl -s  http://$server:$port/start
logs
}

shell(){
  clear
  echo "Running the command....."
   curl -H "Content-Type: application/json" -X POST -d '{"command":"'"$1"'"}' http://$server:$port/exec
   sleep 1
   logs
}


build() {
  clear
  echo "Building the containers....."
  curl -s http://$server:$port/build
  sleep 10
  logs
}


logs(){
  clear
  echo "Checking the logs....."
  curl -s http://$server:$port/log
}

create() {
  clear
  echo "Running the containers....."
curl -s http://$server:$port/create
logs
}

status() {
  clear
  echo "Checking the status....."
curl -s http://$server:$port/status
sleep 5
logs
}


if [  -z "$1" ]; then
echo "Error, no args specified!"
echo
arguments="build start create status exec start stop "
echo "Valid arguments are: $arguments"
echo
exit
fi;

if [ "$1" = "hb" ]; then hb;exit; fi;

if [ "$1" = "exec" ]; then shell "$2";exit; fi;


if [ "$1" = "status" ]; then echo "Gathering Cluster Status....";status;exit; fi;
if [ "$1" = "log" ]; then echo "Gathering Logs....";logs;exit; fi;
if [ "$1" = "build" ]; then echo "Building Images....";build; fi;
if [ "$1" = "start" ]; then echo "Running Containers....";start; fi;
if [ "$1" = "stop" ]; then echo "Stopping Containers....";stop; fi;
if [ "$1" = "create" ]; then echo "Creating Containers....";create; fi;
