#!/bin/bash
clear
server='192.168.0.116'
port='3000'
token='1234567890ABCDEFGHJKLMNOP'

hb(){
clear
echo "Heartbeat is now checking....."
curl -s $server:$port/hb?token=$token
logs
}

nodes(){
clear
echo "Active Nodes:"
curl -s $server:$port/nodes?token=$token
logs
}

stop(){
clear
echo "Stopping the container(s)....."
curl -s -G -d "token=$token&container=$1" http://$server:$port/stop
logs
}

images(){
clear
echo "Gathering a list of images....."
curl -s  http://$server:$port/images?token=$token
logs
}

reloadconfig(){
clear
echo "Reloading the configuration...."
curl -s http://$server:$port/reloadconfig?token=$token
logs
}


shell(){
  clear
  echo "Running the command....."
   curl -H "Content-Type: application/json" -X POST -d '{"command":"'"$1"'","token":"'"$token"'"}' http://$server:$port/exec
   logs
}

clean(){
clear
echo "Cleaning stale Docker images and containers...."
curl -s http://$server:$port/prune?token=$token
logs
}

build() {
  clear
  echo "Building the container(s) in the background. This may take a while. Continue to check the logs for progress."
  curl -s -G -d "token=$token&image=$1" http://$server:$port/build
  logs
}

logs(){
  sleep 5
  clear
  echo "Checking the logs....."
  curl -s http://$server:$port/log?token=$token
}

create() {
clear
echo "Running the container(s)....."
curl -s -G -d "token=$token&container=$1" http://$server:$port/create
logs
}

start(){
clear
echo "Starting the container(s)....."
curl -s -G -d "token=$token&container=$1" http://$server:$port/start
logs
}

restart(){
clear
echo "Restarting the container(s)....."
curl -s -G -d "token=$token&container=$1" http://$server:$port/restart
logs
}

delete(){
clear
echo "Deleting the container(s)....."
curl -s -G -d "token=$token&container=$1" http://$server:$port/delete
logs
}

status() {
  clear
  echo "Checking the status....."
curl -s http://$server:$port/status?token=$token
logs
}


if [  -z "$1" ]; then
echo "Error, no args specified!"
echo
arguments="build nodes reloadconfig images start create status exec start stop clean "
echo "Valid arguments are: $arguments"
echo
exit
fi;

if [ "$1" = "hb" ]; then hb;exit; fi;

if [ "$1" = "exec" ]; then shell "$2";exit; fi;


if [ "$1" = "status" ]; then echo "Gathering Cluster Status....";status;exit; fi;
if [ "$1" = "nodes" ]; then nodes;exit; fi;
if [ "$1" = "clean" ]; then clean;exit; fi;
if [ "$1" = "images" ]; then images;exit; fi;
if [ "$1" = "reloadconfig" ]; then reloadconfig;exit; fi;
if [ "$1" = "log" ]; then echo "Gathering Logs....";logs;exit; fi;
if [ "$1" = "restart" ]; then restart "$2";exit; fi;
if [ "$1" = "delete" ]; then delete "$2";exit; fi;
if [ "$1" = "build" ]; then echo "Building Images....";build "$2"; fi;
if [ "$1" = "start" ]; then echo "Running container(s)....";start "$2"; fi;
if [ "$1" = "stop" ]; then echo "Stopping container(s)....";stop "$2"; fi;
if [ "$1" = "create" ]; then echo "Creating container(s)....";create "$2"; fi;
