# Arch Linux ARM (Raspberry Pi 2)

FROM scratch
MAINTAINER TokinRing <support@gnetsolutions.net>

LABEL Description="Arch Linux ARM (Raspberry Pi 2)"

ADD wget http://os.archlinuxarm.org/os/ArchLinuxARM-rpi-2-latest.tar.gz /
