# Arch Linux ARM (Raspberry Pi 2)

ARG VERSION=latest
FROM scratch AS armhf-archlinux

MAINTAINER TokinRing <support@gnetsolutions.net>
LABEL Description="Arch Linux ARM (Raspberry Pi 2)"

ADD http://os.archlinuxarm.org/os/ArchLinuxARM-rpi-2-latest.tar.gz /
